apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: kassudin/ping-pong:1.5
        env:
          - name: PORT
            value: "3000"
          - name: DATABASE_URL
            value: "postgresql://postgres:x@postgres-svc:5432/postgres"