apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: PROJECT/LOG-OUTPUT-GENERATOR
  newName: kassudin/log-output-generator
  newTag: 76e15e6508d560824cb2878ba5bad9714a61cb09
- name: PROJECT/LOG-READER
  newName: kassudin/log-reader
  newTag: 76e15e6508d560824cb2878ba5bad9714a61cb09
