apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: PROJECT/LOG-OUTPUT-GENERATOR
  newName: kassudin/log-output-generator
  newTag: 04e569c9b99c60fcdece8022f6061030325747ec
- name: PROJECT/LOG-READER
  newName: kassudin/log-reader
  newTag: 04e569c9b99c60fcdece8022f6061030325747ec
