apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: PROJECT/LOG-OUTPUT-GENERATOR
  newName: kassudin/log-output-generator
  newTag: 0276b7e97a5d7f03101f39bca3bf4f40a839286f
- name: PROJECT/LOG-READER
  newName: kassudin/log-reader
  newTag: 0276b7e97a5d7f03101f39bca3bf4f40a839286f
